### ISSUE TITLE
Misspelling in basketball icon tooltip

### ISSUE THREAD

**Issue by christieyoo** [wedeploy/marblecss.com#6]
On http://marblecss.com/docs/components/icon.html page, the basketball icon tooltip is misspelled as "icon-16-dribbble".

**Comment by pragmaticivan** [comment]
@christieyoo probably it's referencing the actually Social networking (https://dribbble.com/)

**Comment by christieyoo** [comment]
@pragmaticivan oh, haha, didn't know about that.  I'll close this.
